import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:uuid/uuid.dart';

class Exercise {
  final String id;
  final String name;
  final double weight;
  final int reps;
  final int bonusReps;
  final String bodyPart;

  Exercise._({
    required this.id,
    required this.name,
    required this.weight,
    required this.reps,
    required this.bonusReps,
    required this.bodyPart,
  });

  factory Exercise({
    String id = "",
    required String name,
    required double weight,
    required int reps,
    required int bonusReps,
    required String bodyPart,
  }) {
    id = id == "" ? const Uuid().v4() : id;
    return Exercise._(
      id: id,
      name: name,
      weight: weight,
      reps: reps,
      bonusReps: bonusReps,
      bodyPart: bodyPart,
    );
  }

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'id': id,
      'name': name,
      'weight': weight,
      'reps': reps,
      'bonusReps': bonusReps,
      'bodyPart': bodyPart,
    };
  }

  factory Exercise.fromMap(Map<String, dynamic> map) {
    return Exercise(
      id: map['id'] as String,
      name: map['name'] as String,
      weight: map['weight'] as double,
      reps: map['reps'] as int,
      bonusReps: map['bonusReps'] as int,
      bodyPart: map['bodyPart'] as String,
    );
  }

  factory Exercise.fromSnapshot(DocumentSnapshot snapshot) {
    return Exercise(
      id: snapshot.id,
      name: snapshot['name'] as String,
      weight: snapshot['weight'] as double,
      reps: snapshot['reps'] as int,
      bonusReps: snapshot['bonusReps'] as int,
      bodyPart: snapshot['bodyPart'] as String,
    );
  }
}

enum BodyParts {
  Biceps,
  Chest,
  Shoulders,
  Triceps,
  Legs,
  Forearms,
  WholeBody,
  Back,
  Core,
}

Map<String, String> exerciseBodypartMap = {
  'Bench Press': 'Chest',
  'Squat': 'Legs',
  'Deadlift': 'WholeBody',
  'Shoulder Press': 'Shoulders',
  'Dumbbell Bench Press': 'Chest',
  'Pull Ups': 'Back',
  'Dumbbell Curl': 'Biceps',
  'Barbell Curl': 'Biceps',
  'Push Ups': 'Chest',
  'Sled Leg Press': 'Legs',
  'Dumbbell Shoulder Press': 'Shoulders',
  'Bent Over Row': 'Back',
  'Incline Bench Press': 'Chest',
  'Incline Dumbbell Bench Press': 'Chest',
  'Front Squat': 'Legs',
  'Dips': 'Triceps',
  'Lat Pulldown': 'Back',
  'Hex Bar Deadlift': 'WholeBody',
  'Power Clean': 'WholeBody',
  'Hip Thrust': 'Legs',
  'Dumbbell Lateral Raise': 'Shoulders',
  'Military Press': 'Shoulders',
  'Chin Ups': 'Back',
  'Sumo Deadlift': 'WholeBody',
  'Horizontal Leg Press': 'Legs',
  'Leg Extension': 'Legs',
  'Romanian Deadlift': 'WholeBody',
  'Dumbbell Row': 'Back',
  'Chest Press': 'Chest',
  'Tricep Pushdown': 'Triceps',
  'Hammer Curl': 'Biceps',
  'Seated Cable Row': 'Back',
  'Clean and Jerk': 'WholeBody',
  'Snatch': 'WholeBody',
  'Close Grip Bench Press': 'Chest',
  'Hack Squat': 'Legs',
  'Seated Leg Curl': 'Legs',
  'Clean': 'WholeBody',
  'EZ Bar Curl': 'Biceps',
  'Dumbbell Bulgarian Split Squat': 'Legs',
  'Seated Shoulder Press': 'Shoulders',
  'Barbell Shrug': 'Back',
  'Push Press': 'Shoulders',
  'Machine Chest Fly': 'Chest',
  'Lying Tricep Extension': 'Triceps',
  'Machine Shoulder Press': 'Shoulders',
  'Decline Bench Press': 'Chest',
  'Dumbbell Fly': 'Chest',
  'Lying Leg Curl': 'Legs',
  'Goblet Squat': 'Legs',
  'T Bar Row': 'Back',
  'Machine Calf Raise': 'Legs',
  'Preacher Curl': 'Biceps',
  'Dumbbell Shrug': 'Back',
  'Tricep Rope Pushdown': 'Triceps',
  'Dumbbell Lunge': 'Legs',
  'Seated Dumbbell Shoulder Press': 'Shoulders',
  'Clean and Press': 'WholeBody',
  'Dumbbell Tricep Extension': 'Triceps',
  'Rack Pull': 'WholeBody',
  'Pendlay Row': 'Back',
  'Cable Bicep Curl': 'Biceps',
  'Vertical Leg Press': 'Legs',
  'Smith Machine Bench Press': 'Chest',
  'Box Squat': 'Legs',
  'Dumbbell Concentration Curl': 'Biceps',
  'Upright Row': 'Shoulders',
  'Dumbbell Front Raise': 'Shoulders',
  'Bodyweight Squat': 'Legs',
  'Tricep Extension': 'Triceps',
  'Bulgarian Split Squat': 'Legs',
  'Sit Ups': 'Core',
  'Dumbbell Romanian Deadlift': 'WholeBody',
  'Seated Calf Raise': 'Legs',
  'Cable Lateral Raise': 'Shoulders',
  'Incline Dumbbell Curl': 'Biceps',
  'Machine Row': 'Back',
  'Arnold Press': 'Shoulders',
  'Smith Machine Squat': 'Legs',
  'Cable Fly': 'Chest',
  'Hang Clean': 'WholeBody',
  'Stiff Leg Deadlift': 'WholeBody',
  'Floor Press': 'Chest',
  'Muscle Ups': 'WholeBody',
  'Good Morning': 'Legs',
  'Hip Abduction': 'Legs',
  'Face Pull': 'Shoulders',
  'Zercher Squat': 'Legs',
  'Incline Dumbbell Fly': 'Chest',
  'Dumbbell Pullover': 'Back',
  'Lying Dumbbell Tricep Extension': 'Triceps',
  'Barbell Lunge': 'Legs',
  'Dumbbell Floor Press': 'Chest',
  'Wrist Curl': 'Forearms',
  'Dumbbell Reverse Fly': 'Back',
  'Seated Dip Machine': 'Triceps',
  'Hip Adduction': 'Legs',
  'Chest Supported Dumbbell Row': 'Back',
  'Cable Crunch': 'Core',
  'Overhead Squat': 'Legs',
  'Machine Seated Crunch': 'Core',
  'Thruster': 'WholeBody',
  'Dumbbell Tricep Kickback': 'Triceps',
  'Power Snatch': 'WholeBody',
  'Barbell Calf Raise': 'Legs',
  'Dumbbell Squat': 'Legs',
  'Push Jerk': 'WholeBody',
  'Machine Bicep Curl': 'Biceps',
  'Split Squat': 'Legs',
  'Reverse Barbell Curl': 'Forearms',
  'Crunches': 'Core',
  'Decline Dumbbell Bench Press': 'Chest',
  'Close Grip Lat Pulldown': 'Back',
  'Paused Bench Press': 'Chest',
  'Machine Reverse Fly': 'Back',
  'Reverse Wrist Curl': 'Forearms',
  'Dumbbell Calf Raise': 'Legs',
  'One Arm Cable Bicep Curl': 'Biceps',
  'Cable Overhead Tricep Extension': 'Triceps',
  'One Arm Push Ups': 'Chest',
  'Reverse Grip Bench Press': 'Chest',
  'Cable Pull Through': 'Legs',
  'Strict Curl': 'Biceps',
  'Standing Leg Curl': 'Legs',
  'Landmine Squat': 'Legs',
  'Dumbbell Deadlift': 'WholeBody',
  'Machine Tricep Extension': 'Triceps',
  'Barbell Reverse Lunge': 'Legs',
  'Barbell Glute Bridge': 'Legs',
  'Dumbbell Wrist Curl': 'Forearms',
  'Diamond Push Ups': 'Chest',
  'Reverse Grip Lat Pulldown': 'Back',
  'Sled Press Calf Raise': 'Legs',
  'Single Leg Press': 'Legs',
  'Single Leg Squat': 'Legs',
  'Deficit Deadlift': 'WholeBody',
  'Neck Curl': 'Shoulders',
  'Dumbbell Upright Row': 'Shoulders',
  'Belt Squat': 'Legs',
  'Straight Arm Pulldown': 'Back',
  'One Arm Dumbbell Preacher Curl': 'Biceps',
  'Safety Bar Squat': 'Legs',
  'Neutral Grip Pull Ups': 'Back',
  'Cable Reverse Fly': 'Back',
  'Close Grip Dumbbell Bench Press': 'Chest',
  'Machine Lateral Raise': 'Shoulders',
  'Behind The Neck Press': 'Shoulders',
  'Handstand Push Ups': 'Shoulders',
  'Barbell Front Raise': 'Shoulders',
  'Yates Row': 'Back',
  'Seated Dumbbell Tricep Extension': 'Triceps',
  'Barbell Hack Squat': 'Legs',
  'Pause Squat': 'Legs',
  'Bench Pin Press': 'Chest',
  'Bench Pull': 'Back',
  'Pistol Squat': 'Legs',
  'Bent Over Dumbbell Row': 'Back',
  'Log Press': 'Shoulders',
  'Back Extension': 'Back',
  'Machine Back Extension': 'Back',
  'Single Leg Romanian Deadlift': 'WholeBody',
  'Split Jerk': 'WholeBody',
  'Hang Power Clean': 'WholeBody',
  'Sumo Squat': 'Legs',
  'Dumbbell Side Bend': 'Core',
  'Burpees': 'WholeBody',
  'Clean High Pull': 'WholeBody',
  'Snatch Deadlift': 'WholeBody',
  'Dumbbell Snatch': 'WholeBody',
  'Incline Hammer Curl': 'Biceps',
  'Cable Woodchopper': 'Core',
  'Barbell Pullover': 'Back',
  'Clean Pull': 'WholeBody',
  'Pause Deadlift': 'WholeBody',
  'Landmine Press': 'Shoulders',
  'Cable Kickback': 'Legs',
  'Reverse Grip Tricep Pushdown': 'Triceps',
  'Spider Curl': 'Biceps',
  'One Arm Pull Ups': 'Back',
  'Single Leg Deadlift': 'WholeBody',
  'Muscle Snatch': 'WholeBody',
  'Wide Grip Bench Press': 'Chest',
  'Jefferson Deadlift': 'WholeBody',
  'Neck Extension': 'Shoulders',
  'Bodyweight Calf Raise': 'Legs',
  'Dumbbell Bench Pull': 'Back',
  'JM Press': 'Triceps',
  'Lunge': 'Legs',
  'Hanging Leg Raise': 'Core',
  'Zottman Curl': 'Biceps',
  'Z Press': 'Shoulders',
  'Renegade Row': 'Back',
  'Viking Press': 'Shoulders',
  'Inverted Row': 'Back',
  'Tate Press': 'Triceps',
  'Shoulder Pin Press': 'Shoulders',
  'Snatch Pull': 'WholeBody',
  'Glute Bridge': 'Legs',
  'Pin Squat': 'Legs',
  'Russian Twist': 'Core',
  'Seated Dumbbell Curl': 'Biceps',
  'Dumbbell Z Press': 'Shoulders',
  'Lying Leg Raise': 'Core',
  'Wall Ball': 'WholeBody',
  'Decline Push Up': 'Chest',
  'Bench Dips': 'Triceps',
  'Ring Dips': 'Triceps',
  'One Arm Lat Pulldown': 'Back',
  'Cheat Curl': 'Biceps',
  'Walking Lunge': 'Legs',
  'Dumbbell Front Squat': 'Legs',
  'Dumbbell Reverse Wrist Curl': 'Forearms',
  'One Arm Seated Cable Row': 'Back',
  'Close Grip Incline Bench Press': 'Chest',
  'Decline Sit Up': 'Core',
  'Hanging Knee Raise': 'Core',
  'Ab Wheel Rollout': 'Core',
  'Cable Hammer Curl': 'Biceps',
  'Dumbbell Split Squat': 'Legs',
  'Reverse Lunge': 'Legs',
  'Cable Upright Row': 'Back',
  'Toes To Bar': 'Core',
  'Squat Jump': 'Legs',
  'Dumbbell Reverse Curl': 'Forearms',
  'Machine Shrug': 'Back',
  'Dumbbell External Rotation': 'Shoulders',
  'Nordic Hamstring Curl': 'Legs',
  'One Arm Landmine Press': 'Shoulders',
  'Zercher Deadlift': 'WholeBody',
  'Dumbbell Push Press': 'Shoulders',
  'Decline Crunch': 'Core',
  'Dumbbell Face Pull': 'Shoulders',
  'Jumping Jack': 'Core',
  'Pike Push Up': 'Shoulders',
  'Hex Bar Shrug': 'Back',
  'Close Grip Push Up': 'Chest',
  'Incline Push Up': 'Chest',
  'Dumbbell Incline Y Raise': 'Back',
  'Smith Machine Shrug': 'Back',
  'Single Leg Dumbbell Deadlift': 'WholeBody',
  'Sissy Squat': 'Legs',
  'Glute Ham Raise': 'Legs',
  'Cable Shrug': 'Back',
  'Single Leg Seated Calf Raise': 'Legs',
  'Bent Arm Barbell Pullover': 'Back',
  'Half Squat': 'Legs',
  'Barbell Power Shrug': 'Back',
  'Cable Leg Extension': 'Legs',
  'Bicycle Crunch': 'Core',
  'Archer Push Ups': 'Chest',
  'Dumbbell Clean and Press': 'WholeBody',
  'Cable External Rotation': 'Shoulders',
  'Reverse Crunches': 'Core',
  'Ring Muscle Ups': 'WholeBody',
  'Side Lunge': 'Legs',
  'Behind The Back Barbell Shrug': 'Back',
  'One Arm Pulldown': 'Biceps',
  'Meadows Row': 'Back',
  'Spoto Press': 'Chest',
  'Dumbbell Thruster': 'WholeBody',
  'Decline Dumbbell Fly': 'Chest',
  'Dumbbell High Pull': 'WholeBody',
  'Hang Snatch': 'WholeBody',
  'Flutter Kicks': 'Core',
  'Glute Kickback': 'Legs',
  'Mountain Climbers': 'Core',
  'Donkey Calf Raise': 'Legs',
  'Dumbbell Hang Clean': 'WholeBody',
  'Dumbbell Walking Calf Raise': 'Legs',
  'Behind The Back Deadlift': 'WholeBody',
  'High Pulley Crunch': 'Core',
  'Clap Pull Up': 'WholeBody',
  'Standing Cable Crunch': 'Core',
  'Reverse Hyperextension': 'Back',
  'Side Leg Raise': 'Legs',
  'Overhead Cable Curl': 'Biceps',
  'Superman': 'Core',
  'Side Crunch': 'Core',
  'Roman Chair Side Bend': 'Core',
  'Jefferson Squat': 'Legs',
  'Floor Hip Abduction': 'Legs',
  'Incline Cable Curl': 'Biceps',
  'Hip Extension': 'Legs',
  'Squat Thrust': 'WholeBody',
  'Scissor Kicks': 'Core',
  'Lying Cable Curl': 'Biceps',
  'Floor Hip Extension': 'Legs'
};

Map<String, String> exerciseImageMap = {
  'Bench Press': 'bench-press-256x256.png',
  'Squat': 'squat-256x256.png',
  'Deadlift': 'deadlift-256x256.png',
  'Shoulder Press': 'shoulder-press-256x256.png',
  'Dumbbell Bench Press': 'dumbbell-bench-press-256x256.png',
  'Pull Ups': 'pull-ups-256x256.png',
  'Dumbbell Curl': 'dumbbell-curl-256x256.png',
  'Barbell Curl': 'barbell-curl-256x256.png',
  'Push Ups': 'push-ups-256x256.png',
  'Sled Leg Press': 'sled-leg-press-256x256.png',
  'Dumbbell Shoulder Press': 'dumbbell-shoulder-press-256x256.png',
  'Bent Over Row': 'bent-over-row-256x256.png',
  'Incline Bench Press': 'incline-bench-press-256x256.png',
  'Incline Dumbbell Bench Press': 'incline-dumbbell-bench-press-256x256.png',
  'Front Squat': 'front-squat-256x256.png',
  'Dips': 'dips-256x256.png',
  'Lat Pulldown': 'lat-pulldown-256x256.png',
  'Hex Bar Deadlift': 'hex-bar-deadlift-256x256.png',
  'Power Clean': 'power-clean-256x256.png',
  'Hip Thrust': 'hip-thrust-256x256.png',
  'Dumbbell Lateral Raise': 'dumbbell-lateral-raise-256x256.png',
  'Military Press': 'military-press-256x256.png',
  'Chin Ups': 'chin-ups-256x256.png',
  'Sumo Deadlift': 'sumo-deadlift-256x256.png',
  'Horizontal Leg Press': 'horizontal-leg-press-256x256.png',
  'Leg Extension': 'leg-extension-256x256.png',
  'Romanian Deadlift': 'romanian-deadlift-256x256.png',
  'Dumbbell Row': 'dumbbell-row-256x256.png',
  'Chest Press': 'chest-press-256x256.png',
  'Tricep Pushdown': 'tricep-pushdown-256x256.png',
  'Hammer Curl': 'hammer-curl-256x256.png',
  'Seated Cable Row': 'seated-cable-row-256x256.png',
  'Clean and Jerk': 'clean-and-jerk-256x256.png',
  'Snatch': 'snatch-256x256.png',
  'Close Grip Bench Press': 'close-grip-bench-press-256x256.png',
  'Hack Squat': 'hack-squat-256x256.png',
  'Seated Leg Curl': 'seated-leg-curl-256x256.png',
  'Clean': 'clean-256x256.png',
  'EZ Bar Curl': 'ez-bar-curl-256x256.png',
  'Dumbbell Bulgarian Split Squat':
      'dumbbell-bulgarian-split-squat-256x256.png',
  'Seated Shoulder Press': 'seated-shoulder-press-256x256.png',
  'Barbell Shrug': 'barbell-shrug-256x256.png',
  'Push Press': 'push-press-256x256.png',
  'Machine Chest Fly': 'machine-chest-fly-256x256.png',
  'Lying Tricep Extension': 'lying-tricep-extension-256x256.png',
  'Machine Shoulder Press': 'machine-shoulder-press-256x256.png',
  'Decline Bench Press': 'decline-bench-press-256x256.png',
  'Dumbbell Fly': 'dumbbell-fly-256x256.png',
  'Lying Leg Curl': 'lying-leg-curl-256x256.png',
  'Goblet Squat': 'goblet-squat-256x256.png',
  'T Bar Row': 't-bar-row-256x256.png',
  'Machine Calf Raise': 'machine-calf-raise-256x256.png',
  'Preacher Curl': 'preacher-curl-256x256.png',
  'Dumbbell Shrug': 'dumbbell-shrug-256x256.png',
  'Tricep Rope Pushdown': 'tricep-rope-pushdown-256x256.png',
  'Dumbbell Lunge': 'dumbbell-lunge-256x256.png',
  'Seated Dumbbell Shoulder Press':
      'seated-dumbbell-shoulder-press-256x256.png',
  'Clean and Press': 'clean-and-press-256x256.png',
  'Dumbbell Tricep Extension': 'dumbbell-tricep-extension-256x256.png',
  'Rack Pull': 'rack-pull-256x256.png',
  'Pendlay Row': 'pendlay-row-256x256.png',
  'Cable Bicep Curl': 'cable-bicep-curl-256x256.png',
  'Vertical Leg Press': 'vertical-leg-press-256x256.png',
  'Smith Machine Bench Press': 'smith-machine-bench-press-256x256.png',
  'Box Squat': 'box-squat-256x256.png',
  'Dumbbell Concentration Curl': 'dumbbell-concentration-curl-256x256.png',
  'Upright Row': 'upright-row-256x256.png',
  'Dumbbell Front Raise': 'dumbbell-front-raise-256x256.png',
  'Bodyweight Squat': 'bodyweight-squat-256x256.png',
  'Tricep Extension': 'tricep-extension-256x256.png',
  'Bulgarian Split Squat': 'bulgarian-split-squat-256x256.png',
  'Sit Ups': 'sit-ups-256x256.png',
  'Dumbbell Romanian Deadlift': 'dumbbell-romanian-deadlift-256x256.png',
  'Seated Calf Raise': 'seated-calf-raise-256x256.png',
  'Cable Lateral Raise': 'cable-lateral-raise-256x256.png',
  'Incline Dumbbell Curl': 'incline-dumbbell-curl-256x256.png',
  'Machine Row': 'machine-row-256x256.png',
  'Arnold Press': 'arnold-press-256x256.png',
  'Smith Machine Squat': 'smith-machine-squat-256x256.png',
  'Cable Fly': 'cable-fly-256x256.png',
  'Hang Clean': 'hang-clean-256x256.png',
  'Stiff Leg Deadlift': 'stiff-leg-deadlift-256x256.png',
  'Floor Press': 'floor-press-256x256.png',
  'Muscle Ups': 'muscle-ups-256x256.png',
  'Good Morning': 'good-morning-256x256.png',
  'Hip Abduction': 'hip-abduction-256x256.png',
  'Face Pull': 'face-pull-256x256.png',
  'Zercher Squat': 'zercher-squat-256x256.png',
  'Incline Dumbbell Fly': 'incline-dumbbell-fly-256x256.png',
  'Dumbbell Pullover': 'dumbbell-pullover-256x256.png',
  'Lying Dumbbell Tricep Extension':
      'lying-dumbbell-tricep-extension-256x256.png',
  'Barbell Lunge': 'barbell-lunge-256x256.png',
  'Dumbbell Floor Press': 'dumbbell-floor-press-256x256.png',
  'Wrist Curl': 'wrist-curl-256x256.png',
  'Dumbbell Reverse Fly': 'dumbbell-reverse-fly-256x256.png',
  'Seated Dip Machine': 'seated-dip-machine-256x256.png',
  'Hip Adduction': 'hip-adduction-256x256.png',
  'Chest Supported Dumbbell Row': 'chest-supported-dumbbell-row-256x256.png',
  'Cable Crunch': 'cable-crunch-256x256.png',
  'Overhead Squat': 'overhead-squat-256x256.png',
  'Machine Seated Crunch': 'machine-seated-crunch-256x256.png',
  'Thruster': 'thruster-256x256.png',
  'Dumbbell Tricep Kickback': 'dumbbell-tricep-kickback-256x256.png',
  'Power Snatch': 'power-snatch-256x256.png',
  'Barbell Calf Raise': 'barbell-calf-raise-256x256.png',
  'Dumbbell Squat': 'dumbbell-squat-256x256.png',
  'Push Jerk': 'push-jerk-256x256.png',
  'Machine Bicep Curl': 'machine-bicep-curl-256x256.png',
  'Split Squat': 'split-squat-256x256.png',
  'Reverse Barbell Curl': 'reverse-barbell-curl-256x256.png',
  'Crunches': 'crunches-256x256.png',
  'Decline Dumbbell Bench Press': 'decline-dumbbell-bench-press-256x256.png',
  'Close Grip Lat Pulldown': 'close-grip-lat-pulldown-256x256.png',
  'Paused Bench Press': 'paused-bench-press-256x256.png',
  'Machine Reverse Fly': 'machine-reverse-fly-256x256.png',
  'Reverse Wrist Curl': 'reverse-wrist-curl-256x256.png',
  'Dumbbell Calf Raise': 'dumbbell-calf-raise-256x256.png',
  'One Arm Cable Bicep Curl': 'one-arm-cable-bicep-curl-256x256.png',
  'Cable Overhead Tricep Extension':
      'cable-overhead-tricep-extension-256x256.png',
  'One Arm Push Ups': 'one-arm-push-ups-256x256.png',
  'Reverse Grip Bench Press': 'reverse-grip-bench-press-256x256.png',
  'Cable Pull Through': 'cable-pull-through-256x256.png',
  'Strict Curl': 'strict-curl-256x256.png',
  'Standing Leg Curl': 'standing-leg-curl-256x256.png',
  'Landmine Squat': 'landmine-squat-256x256.png',
  'Dumbbell Deadlift': 'dumbbell-deadlift-256x256.png',
  'Machine Tricep Extension': 'machine-tricep-extension-256x256.png',
  'Barbell Reverse Lunge': 'barbell-reverse-lunge-256x256.png',
  'Barbell Glute Bridge': 'barbell-glute-bridge-256x256.png',
  'Dumbbell Wrist Curl': 'dumbbell-wrist-curl-256x256.png',
  'Diamond Push Ups': 'diamond-push-ups-256x256.png',
  'Reverse Grip Lat Pulldown': 'reverse-grip-lat-pulldown-256x256.png',
  'Sled Press Calf Raise': 'sled-press-calf-raise-256x256.png',
  'Single Leg Press': 'single-leg-press-256x256.png',
  'Single Leg Squat': 'single-leg-squat-256x256.png',
  'Deficit Deadlift': 'deficit-deadlift-256x256.png',
  'Neck Curl': 'neck-curl-256x256.png',
  'Dumbbell Upright Row': 'dumbbell-upright-row-256x256.png',
  'Belt Squat': 'belt-squat-256x256.png',
  'Straight Arm Pulldown': 'straight-arm-pulldown-256x256.png',
  'One Arm Dumbbell Preacher Curl':
      'one-arm-dumbbell-preacher-curl-256x256.png',
  'Safety Bar Squat': 'safety-bar-squat-256x256.png',
  'Neutral Grip Pull Ups': 'neutral-grip-pull-ups-256x256.png',
  'Cable Reverse Fly': 'cable-reverse-fly-256x256.png',
  'Close Grip Dumbbell Bench Press':
      'close-grip-dumbbell-bench-press-256x256.png',
  'Machine Lateral Raise': 'machine-lateral-raise-256x256.png',
  'Behind The Neck Press': 'behind-the-neck-press-256x256.png',
  'Handstand Push Ups': 'handstand-push-ups-256x256.png',
  'Barbell Front Raise': 'barbell-front-raise-256x256.png',
  'Yates Row': 'yates-row-256x256.png',
  'Seated Dumbbell Tricep Extension':
      'seated-dumbbell-tricep-extension-256x256.png',
  'Barbell Hack Squat': 'barbell-hack-squat-256x256.png',
  'Pause Squat': 'pause-squat-256x256.png',
  'Bench Pin Press': 'bench-pin-press-256x256.png',
  'Bench Pull': 'bench-pull-256x256.png',
  'Pistol Squat': 'pistol-squat-256x256.png',
  'Bent Over Dumbbell Row': 'bent-over-dumbbell-row-256x256.png',
  'Log Press': 'log-press-256x256.png',
  'Back Extension': 'back-extension-256x256.png',
  'Machine Back Extension': 'machine-back-extension-256x256.png',
  'Single Leg Romanian Deadlift': 'single-leg-romanian-deadlift-256x256.png',
  'Split Jerk': 'split-jerk-256x256.png',
  'Hang Power Clean': 'hang-power-clean-256x256.png',
  'Sumo Squat': 'sumo-squat-256x256.png',
  'Dumbbell Side Bend': 'dumbbell-side-bend-256x256.png',
  'Burpees': 'burpees-256x256.png',
  'Clean High Pull': 'clean-high-pull-256x256.png',
  'Snatch Deadlift': 'snatch-deadlift-256x256.png',
  'Dumbbell Snatch': 'dumbbell-snatch-256x256.png',
  'Incline Hammer Curl': 'incline-hammer-curl-256x256.png',
  'Cable Woodchopper': 'cable-woodchopper-256x256.png',
  'Barbell Pullover': 'barbell-pullover-256x256.png',
  'Clean Pull': 'clean-pull-256x256.png',
  'Pause Deadlift': 'pause-deadlift-256x256.png',
  'Landmine Press': 'landmine-press-256x256.png',
  'Cable Kickback': 'cable-kickback-256x256.png',
  'Reverse Grip Tricep Pushdown': 'reverse-grip-tricep-pushdown-256x256.png',
  'Spider Curl': 'spider-curl-256x256.png',
  'One Arm Pull Ups': 'one-arm-pull-ups-256x256.png',
  'Single Leg Deadlift': 'single-leg-deadlift-256x256.png',
  'Muscle Snatch': 'muscle-snatch-256x256.png',
  'Wide Grip Bench Press': 'wide-grip-bench-press-256x256.png',
  'Jefferson Deadlift': 'jefferson-deadlift-256x256.png',
  'Neck Extension': 'neck-extension-256x256.png',
  'Bodyweight Calf Raise': 'bodyweight-calf-raise-256x256.png',
  'Dumbbell Bench Pull': 'dumbbell-bench-pull-256x256.png',
  'JM Press': 'jm-press-256x256.png',
  'Lunge': 'lunge-256x256.png',
  'Hanging Leg Raise': 'hanging-leg-raise-256x256.png',
  'Zottman Curl': 'zottman-curl-256x256.png',
  'Z Press': 'z-press-256x256.png',
  'Renegade Row': 'renegade-row-256x256.png',
  'Viking Press': 'viking-press-256x256.png',
  'Inverted Row': 'inverted-row-256x256.png',
  'Tate Press': 'tate-press-256x256.png',
  'Shoulder Pin Press': 'shoulder-pin-press-256x256.png',
  'Snatch Pull': 'snatch-pull-256x256.png',
  'Glute Bridge': 'glute-bridge-256x256.png',
  'Pin Squat': 'pin-squat-256x256.png',
  'Russian Twist': 'russian-twist-256x256.png',
  'Seated Dumbbell Curl': 'seated-dumbbell-curl-256x256.png',
  'Dumbbell Z Press': 'dumbbell-z-press-256x256.png',
  'Lying Leg Raise': 'lying-leg-raise-256x256.png',
  'Wall Ball': 'wall-ball-256x256.png',
  'Decline Push Up': 'decline-push-up-256x256.png',
  'Bench Dips': 'bench-dips-256x256.png',
  'Ring Dips': 'ring-dips-256x256.png',
  'One Arm Lat Pulldown': 'one-arm-lat-pulldown-256x256.png',
  'Cheat Curl': 'cheat-curl-256x256.png',
  'Walking Lunge': 'walking-lunge-256x256.png',
  'Dumbbell Front Squat': 'dumbbell-front-squat-256x256.png',
  'Dumbbell Reverse Wrist Curl': 'dumbbell-reverse-wrist-curl-256x256.png',
  'One Arm Seated Cable Row': 'one-arm-seated-cable-row-256x256.png',
  'Close Grip Incline Bench Press':
      'close-grip-incline-bench-press-256x256.png',
  'Decline Sit Up': 'decline-sit-up-256x256.png',
  'Hanging Knee Raise': 'hanging-knee-raise-256x256.png',
  'Ab Wheel Rollout': 'ab-wheel-rollout-256x256.png',
  'Cable Hammer Curl': 'cable-hammer-curl-256x256.png',
  'Dumbbell Split Squat': 'dumbbell-split-squat-256x256.png',
  'Reverse Lunge': 'reverse-lunge-256x256.png',
  'Cable Upright Row': 'cable-upright-row-256x256.png',
  'Toes To Bar': 'toes-to-bar-256x256.png',
  'Squat Jump': 'squat-jump-256x256.png',
  'Dumbbell Reverse Curl': 'dumbbell-reverse-curl-256x256.png',
  'Machine Shrug': 'machine-shrug-256x256.png',
  'Dumbbell External Rotation': 'dumbbell-external-rotation-256x256.png',
  'Nordic Hamstring Curl': 'nordic-hamstring-curl-256x256.png',
  'One Arm Landmine Press': 'one-arm-landmine-press-256x256.png',
  'Zercher Deadlift': 'zercher-deadlift-256x256.png',
  'Dumbbell Push Press': 'dumbbell-push-press-256x256.png',
  'Decline Crunch': 'decline-crunch-256x256.png',
  'Dumbbell Face Pull': 'dumbbell-face-pull-256x256.png',
  'Jumping Jack': 'jumping-jack-256x256.png',
  'Pike Push Up': 'pike-push-up-256x256.png',
  'Hex Bar Shrug': 'hex-bar-shrug-256x256.png',
  'Close Grip Push Up': 'close-grip-push-up-256x256.png',
  'Incline Push Up': 'incline-push-up-256x256.png',
  'Dumbbell Incline Y Raise': 'dumbbell-incline-y-raise-256x256.png',
  'Smith Machine Shrug': 'smith-machine-shrug-256x256.png',
  'Single Leg Dumbbell Deadlift': 'single-leg-dumbbell-deadlift-256x256.png',
  'Sissy Squat': 'sissy-squat-256x256.png',
  'Glute Ham Raise': 'glute-ham-raise-256x256.png',
  'Cable Shrug': 'cable-shrug-256x256.png',
  'Single Leg Seated Calf Raise': 'single-leg-seated-calf-raise-256x256.png',
  'Bent Arm Barbell Pullover': 'bent-arm-barbell-pullover-256x256.png',
  'Half Squat': 'half-squat-256x256.png',
  'Barbell Power Shrug': 'barbell-power-shrug-256x256.png',
  'Cable Leg Extension': 'cable-leg-extension-256x256.png',
  'Bicycle Crunch': 'bicycle-crunch-256x256.png',
  'Archer Push Ups': 'archer-push-ups-256x256.png',
  'Dumbbell Clean and Press': 'dumbbell-clean-and-press-256x256.png',
  'Cable External Rotation': 'cable-external-rotation-256x256.png',
  'Reverse Crunches': 'reverse-crunches-256x256.png',
  'Ring Muscle Ups': 'ring-muscle-ups-256x256.png',
  'Side Lunge': 'side-lunge-256x256.png',
  'Behind The Back Barbell Shrug': 'behind-the-back-barbell-shrug-256x256.png',
  'One Arm Pulldown': 'one-arm-pulldown-256x256.png',
  'Meadows Row': 'meadows-row-256x256.png',
  'Spoto Press': 'spoto-press-256x256.png',
  'Dumbbell Thruster': 'dumbbell-thruster-256x256.png',
  'Decline Dumbbell Fly': 'decline-dumbbell-fly-256x256.png',
  'Dumbbell High Pull': 'dumbbell-high-pull-256x256.png',
  'Hang Snatch': 'hang-snatch-256x256.png',
  'Flutter Kicks': 'flutter-kicks-256x256.png',
  'Glute Kickback': 'glute-kickback-256x256.png',
  'Mountain Climbers': 'mountain-climbers-256x256.png',
  'Donkey Calf Raise': 'donkey-calf-raise-256x256.png',
  'Dumbbell Hang Clean': 'dumbbell-hang-clean-256x256.png',
  'Dumbbell Walking Calf Raise': 'dumbbell-walking-calf-raise-256x256.png',
  'Behind The Back Deadlift': 'behind-the-back-deadlift-256x256.png',
  'High Pulley Crunch': 'high-pulley-crunch-256x256.png',
  'Clap Pull Up': 'clap-pull-up-256x256.png',
  'Standing Cable Crunch': 'standing-cable-crunch-256x256.png',
  'Reverse Hyperextension': 'reverse-hyperextension-256x256.png',
  'Side Leg Raise': 'side-leg-raise-256x256.png',
  'Overhead Cable Curl': 'overhead-cable-curl-256x256.png',
  'Superman': 'superman-256x256.png',
  'Side Crunch': 'side-crunch-256x256.png',
  'Roman Chair Side Bend': 'roman-chair-side-bend-256x256.png',
  'Jefferson Squat': 'jefferson-squat-256x256.png',
  'Floor Hip Abduction': 'floor-hip-abduction-256x256.png',
  'Incline Cable Curl': 'incline-cable-curl-256x256.png',
  'Hip Extension': 'hip-extension-256x256.png',
  'Squat Thrust': 'squat-thrust-256x256.png',
  'Scissor Kicks': 'scissor-kicks-256x256.png',
  'Lying Cable Curl': 'lying-cable-curl-256x256.png',
  'Floor Hip Extension': 'floor-hip-extension-256x256.png'
};
