abstract class ExerciseBase {
  ExerciseBase({
    required this.name,
    required this.weight,
    required this.reps,
    required this.bonusReps,
  });

  final dynamic name;
  final int weight;
  final int reps;
  final int bonusReps;
}

class CustomExercise extends ExerciseBase {
  CustomExercise({
    required String name,
    required int weight,
    required int reps,
    required int bonusReps,
  }) : super(name: name, weight: weight, reps: reps, bonusReps: bonusReps);
}

class Exercise extends ExerciseBase {
  Exercise({
    required ExerciseName name,
    required int weight,
    required int reps,
    required int bonusReps,
  }) : super(name: name, weight: weight, reps: reps, bonusReps: bonusReps);
}

enum ExerciseName {
  BenchPress,
  Squat,
  Deadlift,
  DumbbellBenchPress,
  PullUps,
  DumbbellCurl,
  PushUps,
  SledLegPress,
  DumbbellShoulderPress,
  BentOverRow,
  InclineBenchPress,
  InclineDumbbellBenchPress,
  FrontSquat,
  Dips,
  LatPulldown,
  HexBarDeadlift,
  PowerClean,
  HipThrust,
  DumbbellLateralRaise,
  MilitaryPress,
  LegExtension,
  DumbbellRow,
  ChestPress,
  HammerCurl,
  SeatedCableRow,
  CleanAndJerk,
  HackSquat,
  Clean,
  EZBarCurl,
  MachineChestFly,
  LyingTricepExtension,
  MachineShoulderPress,
  DumbbellFly,
  LyingLegCurl,
  GobletSquat,
  PreacherCurl,
  DumbbellShrug,
  TricepRopePushdown,
  CleanAndPress,
  DumbbellTricepExtension,
  RackPull,
  VerticalLegPress,
  UprightRow,
  BodyweightSquat,
  BulgarianSplitSquat,
  InclineDumbbellCurl,
  MachineRow,
  ArnoldPress,
  HangClean,
  FloorPress,
  MuscleUps,
  BarbellLunge,
  DumbbellReverseFly,
  SeatedDipMachine,
  ChestSupportedDumbbellRow,
  OverheadSquat,
  HipAdduction,
  Thruster,
  PowerSnatch,
  SplitSquat,
  Crunches,
  DeclineDumbbellBenchPress,
  CloseGripLatPulldown,
  MachineReverseFly,
  OneArmCableBicepCurl,
  DumbbellCalfRaise,
  OneArmPushUps,
  BarbellGluteBridge,
  ReverseGripLatPulldown,
  SledPressCalfRaise,
  SingleLegSquat,
  SingleLegPress,
  DeficitDeadlift,
  DumbbellUprightRow,
  SafetyBarSquat,
  OneArmDumbbellPreacherCurl,
  CableReverseFly,
  BehindTheNeckPress,
  MachineLateralRaise,
  HandstandPushUps,
  BarbellHackSquat,
  SeatedDumbbellTricepExtension,
  BenchPull,
  LogPress,
  SplitJerk,
  SumoSquat,
  SnatchDeadlift,
  DumbbellSnatch,
  InclineHammerCurl,
  BarbellPullover,
  CableKickback,
  ReverseGripTricepPushdown,
  SpiderCurl,
  BodyweightCalfRaise,
  Lunge,
  HangingLegRaise,
  ShoulderPinPress,
  RussianTwist,
  DeclinePushUp,
  BenchDips,
  HangingKneeRaise,
  AbWheelRollout,
  CableHammerCurl,
  DumbbellReverseCurl,
  ZercherDeadlift,
  PikePushUp,
  DumbbellInclineYRaise,
  SmithMachineShrug,
  DumbbellCleanAndPress,
  GluteKickback,
  BehindTheBackDeadlift,
  ReverseHyperextension,
  OverheadCableCurl,
  JeffersonSquat,
  FloorHipAbduction,
  FloorHipExtension,
}
